# Generated by Django 5.2 on 2025-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('is_suitable', models.BooleanField(default=False)),
                ('job_type', models.CharField(blank=True, choices=[('FT', 'Full\\-time'), ('PT', 'Part\\-time'), ('CT', 'Contract'), ('FL', 'Freelance')], max_length=50, null=True)),
            ],
        ),
    ]
