# Generated by Django 5.2 on 2025-04-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content_hash',
            field=models.TextField(default=''),
        ),
    ]
