# Generated by Django 5.2 on 2025-04-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_job_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('FL', 'Freelance')], max_length=50, null=True),
        ),
    ]
