# Generated by Django 5.2 on 2025-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='job',
            name='beneficiaries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
